
=head1 NAME

pxe-kexec - Read PXE configuration file and kexec entries


=head1 SYNOPSIS

pxe-kexec [options] [I<tftp_server>]


=head1 DESCRIPTION

B<pxe-kexec> is a tool that fetches PXE configuration from a TFTP server,
reads that PXE configuration file, prompts the user for an boot entry,
downloads the specified kernel and initrd and finally tries to boot the
kernel.

The normal process to boot with kexec(8) is that B<pxe-kexec> loads the
kernel and invokes reboot(8). The shutdown script of the Linux distribution
then executes I<kexec -e> at the very end. That is not implemented everywhere.
Therefore, B<pxe-kexec> has a whitelist of Linux distributions that support
reboot with kexec. If the distribution is not on that whitelist, the
program quits with a warning. To bypass that warning, please use the
I<--igore-whitelist> parameter. You can also use the I<--force> parameter
to execute I<kexec -e> to immediately boot the selected kernel, without
invoking shutdown(8).

B<pxe-kexec> meant to be used in an environment where pre-defined PXE
configurations exist but the user wants to use B<kexec> instead of rebooting.

Normally, the I<tftp_server> must be specified as first argument. If there's
no TFTP server specified, B<pxe-kexec> looks in the DHCP info file for the
DHCP server and uses this one as TFTP server. This only works when the TFTP
server is running on the same machine as the DHCP server.


=head1 OPTIONS

Following options can be specified:

=over 7

=item B<-h> | B<--help>

Prints a short help.

=item B<-v> | B<--version>

Prints the version number to standard output.

=item B<-f> | B<--force>

Immediately load the kernel without invoking reboot(8). This does not execute
shutdown scripts, i.e. does not terminate daemons, network connections etc.

=item B<-w> | B<--ignore-whitelist>

Don't check if the detected Linux distribution is on the whitelist of
distributions that have kexec(8) in their shutdown script. Please don't
use that parameter without letting the author know which distribution
you use and how to detect that distribution. Then the distribution can be
added to the whitelist and other users profit from that experience.

=item B<-l> I<label> | B<--label> I<label>

Specifies the label that should be booted. Use that option if you already know
which I<label> you want to boot. This option implies B<--quiet>.

=item B<-i> | B<--interface> I<netif>

Uses I<netif> instead of the first (non-loopback and up) interface that is
found. Example: "eth5".

=item B<-n> | B<--noconfirm>

Don't ask the user for confirmation before booting an entry. Use that option
with care!

=item B<-Y> | B<--dry-run>

Don't execute call to kexec and don't switch the virtual console before
running "kexec -e". Instead, print the information which program would
be executed with which arguments to standard error.

=item B<-q> | B<--quiet>

Don't display the PXE messages that are added in the PXE configuration with
the I<say> keyword. Also don't display messages which PXE configuration files
the downloader tries to fetch.

=item B<-p> | B<--print-distribution>

Only prints the detected Linux distribution and exits. For example:

    Type        : Ubuntu
    Name        : Ubuntu
    Release     : 9.04
    Codename    : jaunty
    Description : Ubuntu 9.04

This option is very useful if your distribution is not on the whitelist
of Linux distributions that support kexec(8) in the reboot scripts and you
want to create a bugreport.

=item B<-D> | B<--debug>

Enable debugging output. That's good for finding (and fixing!) bugs.

=item B<-d> | B<--nodelete>

Keep downloaded files.

=item B<-F> | B<--ftp>

Always use FTP instead of TFTP. Useful for servers that share TFTP root and
FTP root. (Passive) FTP has the advantage that it passes firewalls better
than TFTP.

=back

=head1   EXAMPLES

=over 7

=item B<pxe-kexec I<mydhcp.mydomain.com>>

Try to fetch the PXE configuration from I<mydhcp.mydomain.com>, display
the I<say> messages from that configuration, prompt for an entry, letting
the user confirm that entry and finally boot that entry via kexec(8).

=item B<pxe-kexec -n I<mydhcp.mydomain.com>>

Same as the previous example, but omit the final confirmation step.

=item B<pxe-kexec I<mydhcp.mydomain.com> I<SLES10-install-auto>>

Same as the first example, but don't prompt the user for the label to boot.
Directly boot the I<SLES10-install-auto> label, but letting the user confirm
that he really wants to boot this!

=item B<pxe-kexec -n I<mydhcp.mydomain.com> I<SLES10-install-auto>>

Same as the previous example, but without confirmation.


=back

=head1 AUTHOR

The B<pxe-kexec> program and documentation has been written by Bernhard Walle
E<lt>L<bernhard@bwalle.de>E<gt>.

=head1 BUGS

This program has no bugs. If you find a feature that should be removed,
please report to E<lt>L<bernhard@bwalle.de>E<gt>
if you don't want to create an account.

=head1 SEE ALSO

kexec(8)


=cut

# vim: set spelllang=en_gb spell fdm=marker tw=78:
